name: whitehead-church-app
services:
  - name: web
    dockerfile_path: /Dockerfile
    envs:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_SECRET
        value: ${BETTER_AUTH_SECRET}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_URL
        value: ${APP_URL}
        scope: RUN_AND_BUILD_TIME
    http_port: 3000
    github:
      branch: main
      repo: grantchatterton/whitehead-church-app
    source_dir: /
