name: whitehead-church-app
services:
  - name: web
    dockerfile_path: /Dockerfile
    envs:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_SECRET
        value: ${BETTER_AUTH_SECRET}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_URL
        value: ${APP_URL}
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_ALLOW_EMAIL_SIGNUP
        value: "true"
        scope: RUN_AND_BUILD_TIME
      - key: BETTER_AUTH_APP_NAME
        value: ${BETTER_AUTH_APP_NAME}
        scope: RUN_AND_BUILD_TIME
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: APP_EMAIL_ADDRESS
        value: ${APP_EMAIL_ADDRESS}
        scope: RUN_AND_BUILD_TIME
    http_port: 3000
    github:
      branch: main
      repo: grantchatterton/whitehead-church-app
    source_dir: /
